pipeline {
    agent { label 'jenkins-agent' }

    stages {
        stage('Build') {
            steps {
                echo "Running build..."
                sh 'echo Build successful'
            }
        }

        stage('Test') {
            steps {
                echo "Running tests..."
                sh 'echo Tests passed'
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying..."
                sh 'echo Deployment done' >> log.txt
            }
        }  
    }

    post {
        always {
            sleep 10
            echo "Pipeline finished"
        }
        success {
            echo "Pipeline SUCCESS"
        }
        failure {
            echo "Pipeline FAILED"
        }
    }
}
