pipeline {
    agent any

    tools {
        jdk 'jdk17'
        nodejs 'node16'
    }

    environment {
        SCANNER_HOME = tool 'sonar-scanner'
        IMAGE_NAME = "iamrupeshsingh/netflix:latest"
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/N4si/DevSecOps-Project.git'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar-server') {
                    sh """
                        $SCANNER_HOME/bin/sonar-scanner \
                        -Dsonar.projectName=Netflix \
                        -Dsonar.projectKey=Netflix
                    """
                }
            }
        }

        stage('Quality Gate') {
            steps {
                script {
                    waitForQualityGate abortPipeline: false, credentialsId: 'Sonar-token'
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                sh "npm install"
            }
        }

        stage('OWASP Dependency Check') {
            steps {
                dependencyCheck additionalArguments: '''
                    --scan .
                    --format XML
                    --out .
                    --disableYarnAudit
                    --disableNodeAudit
                ''', odcInstallation: 'DP-Check'

                script {
                    if (fileExists('dependency-check-report.xml')) {
                        dependencyCheckPublisher pattern: 'dependency-check-report.xml'
                    } else {
                        echo "OWASP report not generated"
                    }
                }
            }
        }

        stage('Trivy FS Scan') {
            steps {
                sh "trivy fs . > trivyfs.txt"
            }
        }

        stage('Docker Build & Push') {
            steps {
                script {

                    withCredentials([
                        usernamePassword(
                            credentialsId: 'docker',
                            usernameVariable: 'DOCKER_USER',
                            passwordVariable: 'DOCKER_PASS'
                        )
                    ]) {

                        sh "docker build --build-arg TMDB_V3_API_KEY=79b7277d7e412311c1c9449e74e89edb -t $IMAGE_NAME ."

                        sh '''
                            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        '''

                        sh "docker push $IMAGE_NAME"
                    }
                }
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh "trivy image $IMAGE_NAME > trivyimage.txt"
            }
        }

        stage('Deploy to Container') {
            steps {
                sh """
                    docker rm -f netflix || true
                    docker run -d -p 8081:80 --name netflix $IMAGE_NAME
                """
            }
        }
    }
}
