pipeline {
    agent { label 'built-node' }

    stages {
        stage('Build') {
            steps {
                echo "Running build..."
                sh 'echo Build successful'
            }
        }

        stage('Test') {
            steps {
                echo "Running tests..."
                sh 'echo Tests passed'
            }
        }

        stage('Deploy') {
            steps {
                echo "Deploying..."
                sh 'echo Deployment done'
            }
        }
    }
}
